In [50]:
!git clone https://github.com/iiscleap/Coswara-Data.git

fatal: destination path 'Coswara-Data' already exists and is not an empty directory.


In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns

In [52]:

coswara_data=pd.read_csv("/content/Coswara-Data/20200413/20200413.csv")

In [53]:
coswara_data.head()

id    l_c   a  ... smoker   ht fever
0  vK2bLRNzllXNeyOMudnNSL5cfpG2  India  24  ...    NaN  NaN   NaN
1  bjA2KpSxneNskrLBeqi4bqoTDQl2  India  72  ...    NaN  NaN   NaN
2  FSzobvJqOXf0rI6X05cHqOiU9Mu2  India  54  ...    NaN  NaN   NaN
3  EqDWckxbsETyHUeBLQ8jLtxlhir2  India  31  ...    NaN  NaN   NaN
4  FGRDO4IBbAejR0WHD5YbkXTCasg2  India  26  ...    NaN  NaN   NaN

[5 rows x 15 columns]

In [54]:

print(coswara_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            76 non-null     object
 1   l_c           76 non-null     object
 2   a             76 non-null     int64 
 3   covid_status  76 non-null     object
 4   iF            76 non-null     bool  
 5   ep            76 non-null     object
 6   g             76 non-null     object
 7   l_s           76 non-null     object
 8   dT            76 non-null     object
 9   l_l           71 non-null     object
 10  diabetes      3 non-null      object
 11  asthma        4 non-null      object
 12  smoker        10 non-null     object
 13  ht            5 non-null      object
 14  fever         1 non-null      object
dtypes: bool(1), int64(1), object(13)
memory usage: 8.5+ KB
None


In [55]:
print('data columns with null values:\n', coswara_data.isnull().sum())

data columns with null values:
 id               0
l_c              0
a                0
covid_status     0
iF               0
ep               0
g                0
l_s              0
dT               0
l_l              5
diabetes        73
asthma          72
smoker          66
ht              71
fever           75
dtype: int64


In [56]:
data2=coswara_data.copy()
data=coswara_data.copy()

In [57]:
data['l_c'].value_counts()


India            70
Canada            3
United States     2
Argentina         1
Name: l_c, dtype: int64

In [58]:


data['l_c']=data['l_c'].map({'India':1,'Canada':0,'United States':2, 'Argentina':3})
print(data['l_c'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: l_c, Length: 76, dtype: int64


In [59]:
data['iF'].value_counts()


True    76
Name: iF, dtype: int64

In [60]:
data['iF']=data['iF']. astype(int)
print(data['iF'])


0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: iF, Length: 76, dtype: int64


In [61]:
data['ep'].value_counts()

y    75
n     1
Name: ep, dtype: int64

In [62]:
data['ep']=data['ep'].map({'y':1,'n':0})
print(data['ep'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: ep, Length: 76, dtype: int64


In [63]:
data['g'].value_counts()

male      59
female    17
Name: g, dtype: int64

In [64]:
data['g']=data['g'].map({'female':1,'male':0})
print(data['g'])

0     0
1     0
2     0
3     0
4     0
     ..
71    0
72    0
73    0
74    1
75    0
Name: g, Length: 76, dtype: int64


In [65]:
data['l_s'].value_counts()

Karnataka         27
Maharashtra       10
Rajasthan          5
Telangana          5
Gujarat            5
Kerala             4
Ontario            3
Andhra Pradesh     3
Chandigarh         2
Uttar Pradesh      2
Haryana            2
Assam              1
Delhi              1
Madhya Pradesh     1
Tamil Nadu         1
California         1
Buenos Aires       1
Georgia            1
West Bengal        1
Name: l_s, dtype: int64

In [66]:

data['l_s']=data['l_s'].map({'Karnataka':1,'Maharashtra':0,'Rajasthan':2,'Telangana':3,'Gujarat':4,'Kerala':5, 'Ontario':6, 'Andhra Pradesh':7, 'Haryana':8, 'Chandigarh':9,'Uttar Pradesh':10,
                                 'Tamil Nadu':11,'West Bengal':12, 'Assam':13, 'Buenos Aires':14, 'California':15, 'Georgia':16, 'Delhi':17, 'Madhya Pradesh':18})
print(data['l_s'])

0      1
1      0
2      0
3      1
4      8
      ..
71     4
72     1
73     5
74     4
75    10
Name: l_s, Length: 76, dtype: int64


In [67]:
data['dT'].value_counts()

web    76
Name: dT, dtype: int64

In [68]:
data['dT']=data['dT'].map({'web':1})
print(data['dT'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: dT, Length: 76, dtype: int64


In [69]:
data['l_l'].value_counts()

Bangalore                                    10
Bangalore                                     5
Udaipur                                       2
Pune                                          2
Chandigarh                                    2
Udaipur                                       2
Ahmedabad                                     2
Trivandrum                                    2
Hyderabad                                     2
Kurnool                                       2
Mumbai                                        2
Forsyth                                       1
Etobicoke                                     1
Brampton                                      1
Bangalore urban                               1
Geddahalli                                    1
Gandhinagar                                   1
Chennai                                       1
Aligarh                                       1
Janakpuri                                     1
Thanke                                  

In [70]:
data['l_l']= data['l_l'].map({'Bangalore':0, 'Trivandrum':1, 'Hyderabad':2, 'Mumbai':3, 'Udaipur':4, 'Ahmedabad':5, 'Chandigarh':6, 'Kurnool':7, 'Pune':8, 'Brampton':9, 'Jayanagar':10,
                          'Bangalore J P Ngar':11, 'Bangalore urban':12, 'Geddahalli':13, 'Chennai':14, 'Thane':15, 'North 24 parganas':16, 'Nizamabad':17, 'Etobicoke':18, 'Alameda':19, 'test_shreyasr_krpuram':20,
                          'Janakpuri':21, 'Toronto':22, 'Thane West':23, 'Hoodi':24, 'Gurgaon':25, 'Aligarh':26, 'Sonebhadra':27, 'Virar/Palghar':28, 'HYDERABAD':29, 'Kadapa':30,
                          'Thanke':31, 'Test':32, 'Jabalpur':33, 'bangalore':34, 'Mandya':35, 'Kollam':36, 'Gachibowli':37, 'Virar':38, 'gurgaon':39, 'Buenos aires':40,'Chittorgarh':41, 
                          'Pincode 380061':42, 'Gandhinagar':43, 
                          'test_shreyasr_krpuram_firefox_samsungm30s':44, 
                          'Forsyth':45}) 
print(data['l_l'])                               

0      NaN
1     15.0
2     23.0
3      0.0
4     39.0
      ... 
71    43.0
72     0.0
73     1.0
74     NaN
75    27.0
Name: l_l, Length: 76, dtype: float64


In [71]:
data['diabetes'].value_counts()

True    3
Name: diabetes, dtype: int64

In [72]:
import random
import numpy as np

data['diabetes'].fillna(True, inplace=True)

In [73]:

data['diabetes']=data['diabetes'].astype(int)
print(data['diabetes'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: diabetes, Length: 76, dtype: int64


In [74]:
data['asthma'].value_counts()

True    4
Name: asthma, dtype: int64

In [75]:
data['asthma'].fillna(True, inplace=True)

In [76]:
data['asthma']=data['asthma']. astype(int)
print(data['asthma'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: asthma, Length: 76, dtype: int64


In [77]:
data['smoker'].value_counts()

True    10
Name: smoker, dtype: int64

In [78]:
data['smoker'].fillna(True, inplace=True)

In [79]:
data['smoker']=data['smoker']. astype(int)
print(data['smoker'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: smoker, Length: 76, dtype: int64


In [80]:
data['ht'].value_counts()

True    5
Name: ht, dtype: int64

In [81]:
data['ht'].fillna(True, inplace=True)

In [82]:

data['ht']=data['ht']. astype(int)
print(data['ht'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: ht, Length: 76, dtype: int64


In [83]:
data['fever'].value_counts()

True    1
Name: fever, dtype: int64

In [84]:
data['fever'].fillna(True, inplace=True)

In [85]:

data['fever']=data['fever']. astype(int)
print(data['fever'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    1
73    1
74    1
75    1
Name: fever, Length: 76, dtype: int64


In [86]:
data['covid_status'].value_counts()

healthy                        66
resp_illness_not_identified     5
no_resp_illness_exposed         5
Name: covid_status, dtype: int64

In [87]:
data['covid_status']=data['covid_status'].map({'healthy':1,'no_resp_illness_exposed':2,
                                               'resp_illness_not_identified':0})
print(data['covid_status'])

0     1
1     1
2     1
3     1
4     1
     ..
71    1
72    0
73    1
74    2
75    1
Name: covid_status, Length: 76, dtype: int64


In [88]:
column_list=list(data.columns)
print(column_list)

['id', 'l_c', 'a', 'covid_status', 'iF', 'ep', 'g', 'l_s', 'dT', 'l_l', 'diabetes', 'asthma', 'smoker', 'ht', 'fever']


In [89]:
features=list(set(column_list)-set(['covid_status']))
print(features)

['g', 'l_s', 'ep', 'ht', 'dT', 'id', 'l_l', 'diabetes', 'l_c', 'a', 'asthma', 'smoker', 'fever', 'iF']


In [90]:
features=list(set(features)-set(['id']))
print(features)

['g', 'l_s', 'ep', 'ht', 'dT', 'l_l', 'diabetes', 'l_c', 'a', 'asthma', 'smoker', 'fever', 'iF']


In [91]:
y=data['covid_status'].values

In [92]:
x=data[features].values

In [93]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [94]:
cols=['id']
data=data.drop(cols,axis=1)


In [95]:
import tensorflow as tf
tf.convert_to_tensor(x_train,dtype=tf.float32)
tf.convert_to_tensor(x_test)
tf.convert_to_tensor(y_train)
tf.convert_to_tensor(y_test)

<tf.Tensor: shape=(16,), dtype=int64, numpy=array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>

In [96]:
from tensorflow import keras
from keras.layers import Dense
from keras.layers import Flatten
model = keras.Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(392,activation='relu'))
model.add(Dense(150,activation='relu'))
model.add(Dense(50,activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam', metrics=['accuracy'])
history=model.fit(x_train,y_train, epochs=10,validation_split=0.1)

Epoch 1/10
2/2 [==============================] - 3s 145ms/step - loss: nan - accuracy: 0.0370 - val_loss: nan - val_accuracy: 0.1667
Epoch 2/10
2/2 [==============================] - 0s 18ms/step - loss: nan - accuracy: 0.0741 - val_loss: nan - val_accuracy: 0.1667
Epoch 3/10
2/2 [==============================] - 0s 17ms/step - loss: nan - accuracy: 0.0741 - val_loss: nan - val_accuracy: 0.1667
Epoch 4/10
2/2 [==============================] - 0s 17ms/step - loss: nan - accuracy: 0.0741 - val_loss: nan - val_accuracy: 0.1667
Epoch 5/10
2/2 [==============================] - 0s 17ms/step - loss: nan - accuracy: 0.0741 - val_loss: nan - val_accuracy: 0.1667
Epoch 6/10
2/2 [==============================] - 0s 17ms/step - loss: nan - accuracy: 0.0741 - val_loss: nan - val_accuracy: 0.1667
Epoch 7/10
2/2 [==============================] - 0s 17ms/step - loss: nan - accuracy: 0.0741 - val_loss: nan - val_accuracy: 0.1667
Epoch 8/10
2/2 [==============================] - 0s 17ms/step - los

In [97]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred=model.predict_classes(x_test)

print(confusion_matrix(y_pred,y_test))
print(f'accuracy: {accuracy_score(y_pred, y_test)*100}')

[[ 0 15  1]
 [ 0  0  0]
 [ 0  0  0]]
accuracy: 0.0


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
